name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Create Docker Network
        run: docker network create nodejs-network || true

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

      - name: Delete old container
        run: docker rm -f reactjs-app-container || true

      - name: Run Docker Container
        # This command runs the React container and connects it to the same network
        # as the Node.js container. It also passes an environment variable
        # so the React app knows the backend's address.
        run: >
          docker run -d -p 5001:5173
          --name reactjs-app-container
          --network nodejs-network
          -e VITE_API_URL=http://nodejs-app-container:5000
          ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest