name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Source
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/reactjs-app"
          docker build -t $IMAGE_NAME:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/reactjs-app"
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      # Pull the latest Docker image
      - name: Pull Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/reactjs-app"
          docker pull $IMAGE_NAME:latest

      # Remove old container if exists
      - name: Delete old container
        run: docker rm -f reactjs-app-container || true

      # Run the Docker container
      - name: Run Docker Container
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/reactjs-app"
          docker run -d -p 5001:5173 --name reactjs-app-container $IMAGE_NAME:latest
